# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/qtavdecc.ui'
#
# Created: Tue Jul 22 19:18:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from bezier import BezierDrawer

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QtAVDECC(object):
    def setupUi(self, QtAVDECC):
        QtAVDECC.setObjectName(_fromUtf8("QtAVDECC"))
        QtAVDECC.resize(800, 600)
        self.centralwidget = QtGui.QWidget(QtAVDECC)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 761, 531))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidget = QtGui.QTabWidget(self.verticalLayoutWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.cm_acmp = QtGui.QWidget()
        self.cm_acmp.setObjectName(_fromUtf8("cm_acmp"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.cm_acmp)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 751, 421))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.treeView = QtGui.QTreeView(self.verticalLayoutWidget_2)
        self.treeView.setMinimumSize(QtCore.QSize(100, 300))
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.horizontalLayout.addWidget(self.treeView)
        self.frame = BezierDrawer(self.verticalLayoutWidget_2)
        self.frame.setMinimumSize(QtCore.QSize(100, 300))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout.addWidget(self.frame)
        self.treeView_2 = QtGui.QTreeView(self.verticalLayoutWidget_2)
        self.treeView_2.setMinimumSize(QtCore.QSize(100, 300))
        self.treeView_2.setObjectName(_fromUtf8("treeView_2"))
        self.horizontalLayout.addWidget(self.treeView_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_5 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_2.addWidget(self.pushButton_8, 1, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.cm_acmp, _fromUtf8(""))
        self.rt_ctrl_aecp = QtGui.QWidget()
        self.rt_ctrl_aecp.setObjectName(_fromUtf8("rt_ctrl_aecp"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.rt_ctrl_aecp)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 751, 431))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.treeView_3 = QtGui.QTreeView(self.horizontalLayoutWidget_2)
        self.treeView_3.setObjectName(_fromUtf8("treeView_3"))
        self.horizontalLayout_2.addWidget(self.treeView_3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_9 = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_3.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.checkBox = QtGui.QCheckBox(self.horizontalLayoutWidget_2)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridLayout_3.addWidget(self.checkBox, 1, 1, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.horizontalLayoutWidget_2)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout_3.addWidget(self.spinBox, 1, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_3.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.dial = QtGui.QDial(self.horizontalLayoutWidget_2)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.gridLayout_3.addWidget(self.dial, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_3.addWidget(self.horizontalSlider, 2, 1, 1, 1)
        self.verticalSlider = QtGui.QSlider(self.horizontalLayoutWidget_2)
        self.verticalSlider.setMinimumSize(QtCore.QSize(20, 20))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.gridLayout_3.addWidget(self.verticalSlider, 2, 2, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.rt_ctrl_aecp, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        QtAVDECC.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(QtAVDECC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        QtAVDECC.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(QtAVDECC)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        QtAVDECC.setStatusBar(self.statusbar)
        self.actionPreferences = QtGui.QAction(QtAVDECC)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionExit = QtGui.QAction(QtAVDECC)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAboutPyQtAVDECC = QtGui.QAction(QtAVDECC)
        self.actionAboutPyQtAVDECC.setObjectName(_fromUtf8("actionAboutPyQtAVDECC"))
        self.actionHelp = QtGui.QAction(QtAVDECC)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionGithub_PyQtAVDECC = QtGui.QAction(QtAVDECC)
        self.actionGithub_PyQtAVDECC.setObjectName(_fromUtf8("actionGithub_PyQtAVDECC"))
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPreferences)
        self.menuHelp.addAction(self.actionAboutPyQtAVDECC)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionGithub_PyQtAVDECC)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(QtAVDECC)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(QtAVDECC)

    def retranslateUi(self, QtAVDECC):
        QtAVDECC.setWindowTitle(_translate("QtAVDECC", "PyQtAVDECC", None))
        self.pushButton.setText(_translate("QtAVDECC", "Packet Capture", None))
        self.pushButton_2.setText(_translate("QtAVDECC", "PushButton", None))
        self.pushButton_3.setText(_translate("QtAVDECC", "PushButton", None))
        self.pushButton_4.setText(_translate("QtAVDECC", "PushButton", None))
        self.label_3.setText(_translate("QtAVDECC", "Talker", None))
        self.label_2.setText(_translate("QtAVDECC", "Connection", None))
        self.label_4.setText(_translate("QtAVDECC", "Listener", None))
        self.pushButton_5.setText(_translate("QtAVDECC", "Connect", None))
        self.pushButton_6.setText(_translate("QtAVDECC", "Refresh", None))
        self.pushButton_7.setText(_translate("QtAVDECC", "Disconnect", None))
        self.pushButton_8.setText(_translate("QtAVDECC", "PushButton", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cm_acmp), _translate("QtAVDECC", "Connection Management", None))
        self.pushButton_9.setText(_translate("QtAVDECC", "PushButton", None))
        self.checkBox.setText(_translate("QtAVDECC", "CheckBox", None))
        self.label.setText(_translate("QtAVDECC", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rt_ctrl_aecp), _translate("QtAVDECC", "Realtime Controller", None))
        self.menuFile.setTitle(_translate("QtAVDECC", "File", None))
        self.menuEdit.setTitle(_translate("QtAVDECC", "Edit", None))
        self.menuHelp.setTitle(_translate("QtAVDECC", "Help", None))
        self.actionPreferences.setText(_translate("QtAVDECC", "Preferences", None))
        self.actionExit.setText(_translate("QtAVDECC", "Exit", None))
        self.actionAboutPyQtAVDECC.setText(_translate("QtAVDECC", "About PyQtAVDECC", None))
        self.actionHelp.setText(_translate("QtAVDECC", "Help", None))
        self.actionGithub_PyQtAVDECC.setText(_translate("QtAVDECC", "Github PyQtAVDECC", None))

